language: java
sudo: false
install: true


jdk:
- openjdk8

script:
  - mvn clean verify 

cache:
  directories:
  - "$HOME/.m2/repository"

notifications:
  email:
    - jep0042@posteo.de

after_success:
  - bash <(curl -s https://codecov.io/bash)